### ISSUE TITLE
"ORADEA" is a locality in "BIHOR" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#1075]
**Description**

Check that the locality is displayed in the search bar in accordance with Act 2 02/16/1968

**Comment by chiparca81** [comment]
**Precondition**

Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps 1**

Acces to the link https://peviitor-ro.github.io/ui.orase/

**Expected result**

The page opens

**Comment by chiparca81** [comment]
**Steps 2** 

Write "ORADEA"

**Expected result**

In the drop down menu you find "ORADEA, BIHOR"

**Test Data**

ORADEA

**Comment by Florin201092** [comment]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "Oradea" in the search bar

EXPECTED RESULTS:
The location is listed in the drop-down menu as "Municipiul Oradea, Bihor".

ACTUAL RESULTS:
There are two options instead of one. The user should be able to see only "Municipiul Oradea, Bihor".



![Image](https://github.com/peviitor-ro/ui.orase/assets/23164347/6c4b6c65-a744-499f-a8e5-4082bf7ccb49)



From law:
![Image](https://github.com/peviitor-ro/ui.orase/assets/23164347/4352fbd8-8801-4e94-ae77-b4cf5db32d93)
