### ISSUE TITLE
”Târgu Logrești”, ”Colțești”, "Frunza", "Logrești-Moșteni", "Măru", "Popești", "Seaca" are listed in the drop-down menu

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/ui.orase#4209]
**Description:** 
”Târgu Logrești”, ”Colțești”, "Frunza", "Logrești-Moșteni", "Măru", "Popești", "Seaca" are listed in the drop-down menu alongside their corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by iBixee** [comment]
> **Step 1**
Write in the search bar "Târgu Logrești"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Târgu Logrești, GORJ (Logrești)".

**Comment by iBixee** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by iBixee** [comment]
> **Step 3**
Write in the search bar "Colțești"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Colțești, GORJ (Logrești)".

**Comment by iBixee** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by iBixee** [comment]
> **Step 5**
Write in the search bar "Frunza"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Frunza, GORJ (Logrești)".

**Comment by iBixee** [comment]
> **Step 6**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by iBixee** [comment]
> **Step 7**
Write in the search bar "Logrești-Moșteni"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Logrești-Moșteni, GORJ (Logrești)".

**Comment by iBixee** [comment]
> **Step 8**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by iBixee** [comment]
> **Step 9**
Write in the search bar "Măru"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Măru, GORJ (Logrești)".

**Comment by iBixee** [comment]
> **Step 10**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by iBixee** [comment]
> **Step 11**
Write in the search bar "Popești"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Popești, GORJ (Logrești)".

**Comment by iBixee** [comment]
> **Step 12**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by iBixee** [comment]
> **Step 13**
Write in the search bar "Seaca"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Seaca, GORJ (Logrești)".

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 4209
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC :”Târgu Logrești”, ”Colțești”, "Frunza", "Logrești-Moșteni", "Măru", "Popești", "Seaca" are listed in the drop-down menu
[#4209](https://github.com/peviitor-ro/ui.orase/issues/4209)

Expected results:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed : 
"Sat Târgu Logrești, GORJ (Logrești)"
"Sat Colțești, GORJ (Logrești)"
"Sat Frunza, GORJ (Logrești)"
"Sat Logrești-Moșteni, GORJ (Logrești)"
"Sat Măru, GORJ (Logrești)"
"Sat Popești, GORJ (Logrești)"
"Sat Popești, GORJ (Logrești)"


Actual result (displayed):
All STEPS (from 1 to 7) have "Târgu Logrești" instead of "Logrești" - see below screenshot

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/83fb1ab8-902f-4d2b-970c-91ef76865150)

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/e7772140-e0c3-4483-bc5f-b43cd2617d8e)

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/4e8c9e61-f123-484d-a300-27ed4833bc8a)

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/6afec98e-6e12-41d6-8335-c4576964827d)

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/8096b97a-bdf2-402b-b27a-72b3a5c5e43e)

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/42d3d30a-e8c4-40b1-b88b-2d67672bb05a)

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/2b7ea196-0924-4c8f-b47d-f67850facf87)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi
