### ISSUE TITLE
"Florești", "Luna de Sus", "Tăuți" are listed in the drop-down

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/ui.orase#4357]
Description:
When user writes "Florești", "Luna de Sus" and "Tăuți" the locations appear in the drop-down menu next to the comune and the county which is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by SimonaNemtanu** [comment]
Step 1
Write in the search bar "Florești"

Expected results
The location appears in the drop-down menu as "Sat Florești, CLUJ (Ciurila)"

**Comment by SimonaNemtanu** [comment]
Step 2
Press "x" button.

Expected results
The location was deleted from the search bar.

**Comment by SimonaNemtanu** [comment]
Step 3
Write in the search bar "Luna de Sus"

Expected results
The location appears in the drop-down menu as "Sat Luna de Sus, CLUJ (Ciurila)"

**Comment by SimonaNemtanu** [comment]
Step 4
Press "x" button.

Expected results
The location was deleted from the search bar.

**Comment by SimonaNemtanu** [comment]
Step 5
Write in the search bar "Tăuți"

Expected results
The location appears in the drop-down menu as "Tăuți, CLUJ (Ciurila)"

**Comment by dapatrut** [comment]
ENVIROMENT: Run Tests: 4357
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Google Chrome
OS: Windows 10 Pro

STEPS TO REPRODUCE:
1. Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC : "Florești", "Luna de Sus", "Tăuți" are listed in the drop-down
#4357

EXPECTED RESULTS:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed :
STEP1: According to the law , the locations should appear in the drop-down menu as "Sat Florești,CLUJ(Florești)".

![Image](https://github.com/peviitor-ro/ui.orase/assets/131185490/90f254a2-ebb3-4a26-a252-28b60f308e22)

STEP3: According to the law , the locations should appear in the drop-down menu as "Sat Luna de Sus, CLUJ (Florești)".

![Image](https://github.com/peviitor-ro/ui.orase/assets/131185490/1f40a967-f72e-4d09-89f2-cfdbf0e1df69)

STEP5: According to the law , the locations should appear in the drop-down menu as "Sat Tăuți, CLUJ (Florești)".

![Image](https://github.com/peviitor-ro/ui.orase/assets/131185490/027b6e76-9f30-46d0-a088-fad0e267bedc)

![Image](https://github.com/peviitor-ro/ui.orase/assets/131185490/c8caf528-58e0-4969-b07e-da416505af5e)


ACTUAL RESULTS:
STEPS (1, 3 and 5) have "(Ciurila)" instead of "(Floresti)".

**Comment by SimonaNemtanu** [comment]
@dapatrut please, retest

**Comment by AdelinaGuliman** [comment]
@dapatrut please remove the bug and FAIL labels if the TC is PASS

**Comment by dapatrut** [comment]
done
