### ISSUE TITLE
"Popești, Bistra, Budoi, Cuzap, Varviz, Vărzari, Voivozi" are villages in "Popești" commune, "BIHOR" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#4405]
**Description**

When an user search a location, this appear in the drop-down menu
according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition**

The website ( https://peviitor-ro.github.io/ui.orase/ ) is up an running.
Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps**

Write "Popești"

**Expected result**

In the drop down menu you find " **Village**Popești , BIHOR(Popești)"

**Test Data**

Popești

**Comment by chiparca81** [comment]
**Steps 2**

Write "Bistra"

**Expected result**

In the drop down menu you find "**Village** Bistra, **BIHOR**(Popești)"

**Test Data**

Bistra

**Comment by chiparca81** [comment]
**Steps 3**

Write "Budoi"

**Expected result**

In the drop down menu you find "**Village** Budoi, **BIHOR**(Popești)"

**Test Data**

Budoi

**Comment by chiparca81** [comment]
**Steps 4**

Write "Cuzap"

**Expected result**

In the drop down menu you find "**Village** Cuzap, **BIHOR**(Popești)"

**Test Data**

Cuzap

**Comment by chiparca81** [comment]
**Steps 5**

Write "Varviz"

**Expected result**

In the drop down menu you find "**Village** Varviz, **BIHOR**(Popești)"

**Test Data**

Varviz

**Comment by chiparca81** [comment]
**Steps 6**

Write "Vărzari"

**Expected result**

In the drop down menu you find "**Village** Vărzari, **BIHOR**(Popești)"

**Test Data**

Vărzari

**Comment by chiparca81** [comment]
**Steps 7**

Write "Voivozi"

**Expected result**

In the drop down menu you find "**Village** Voivozi, **BIHOR**(Popești)"

**Test Data**

Voivozi

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 4365
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC : Popești, Bistra, Budoi, Cuzap, Varviz, Vărzari, Voivozi" are villages in "Popești" commune, "BIHOR" county
[#4405](https://github.com/peviitor-ro/ui.orase/issues/4405)

Expected results:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed : "Sat Popești, BIHOR (Popești))"

Actual result (displayed):
The STEP have request to displayed "Village Popești, BIHOR(Popești)"

**All STEP's have VILLAGE instead of SAT**
