### ISSUE TITLE
"Răbăgani, Albești, Brătești, Săliște de Pomezeu, Săucani, Vărășeni" are villages in "Răbăgani" commune, "BIHOR" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#4416]
**Description**

When an user search a location, this appear in the drop-down menu
according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition**

The website ( https://peviitor-ro.github.io/ui.orase/ ) is up an running.
Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps**

Write "Răbăgani"

**Expected result**

In the drop down menu you find "**Village** , **BIHOR**(Răbăgani)"

**Test Data**

Răbăgani

**Comment by chiparca81** [comment]
**Steps**

Write ""

**Expected result**

In the drop down menu you find "**Village** , **BIHOR**(Răbăgani)"

**Test Data**

**Comment by chiparca81** [comment]
**Steps 3**

Write "Brătești"

**Expected result**

In the drop down menu you find "**Village** Brătești, **BIHOR**(Răbăgani)"

**Test Data**

Brătești

**Comment by chiparca81** [comment]
**Steps 4**

Write "Săliște de Pomezeu"

**Expected result**

In the drop down menu you find "**Village** Săliște de Pomezeu, **BIHOR**(Răbăgani)"

**Test Data**

Săliște de Pomezeu

**Comment by chiparca81** [comment]
**Steps 5**

Write "Săucani"

**Expected result**

In the drop down menu you find "**Village** Săucani, **BIHOR**(Răbăgani)"

**Test Data**

Săucani

**Comment by chiparca81** [comment]
**Steps 6**

Write "Vărășeni"

**Expected result**

In the drop down menu you find "**Village** Vărășeni, **BIHOR**(Răbăgani)"

**Test Data**

Vărășeni

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 4416
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC : "Răbăgani, Albești, Brătești, Săliște de Pomezeu, Săucani, Vărășeni" are villages in "Răbăgani" commune, "BIHOR" county
[#4416](https://github.com/peviitor-ro/ui.orase/issues/4416)

Expected results:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed : "Sat Răbăgani, BIHOR (Răbăgani)"

Actual result (displayed):
The STEP have request to displayed "Village Răbăgani, BIHOR(Răbăgani)"

All STEPS (from 1 to 6) have "VILLAGE" instead of "SAT"
