### ISSUE TITLE
"Remetea, Drăgoteni, Meziad, Petreasa, Șoimuș" are villages in "Remetea" commune, "BIHOR" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#4424]
**Description**

When an user search a location, this appear in the drop-down menu
according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition**

The website ( https://peviitor-ro.github.io/ui.orase/ ) is up an running.
Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps 1**

Write "Remetea"

**Expected result**

In the drop down menu you find "**Village** Remetea, **BIHOR**(Remetea)"

**Test Data**

Remetea

**Comment by chiparca81** [comment]
**Steps 2**

Write "Drăgoteni"

**Expected result**

In the drop down menu you find "**Village** Drăgoteni, **BIHOR**(Remetea)"

**Test Data**

Drăgoteni

**Comment by chiparca81** [comment]
**Steps 3**

Write "Meziad"

**Expected result**

In the drop down menu you find "**Village** Meziad, **BIHOR**(Remetea)"

**Test Data**

Meziad

**Comment by chiparca81** [comment]
**Steps 4**

Write "Petreasa"

**Expected result**

In the drop down menu you find "**Village** Petreasa, **BIHOR**(Remetea)"

**Test Data**

Petreasa

**Comment by chiparca81** [comment]
**Steps 5**

Write " Șoimuș"

**Expected result**

In the drop down menu you find "**Village**  Șoimuș, **BIHOR**(Remetea)"

**Test Data**

 Șoimuș

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 4424
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC : "Remetea, Drăgoteni, Meziad, Petreasa, Șoimuș" are villages in "Remetea" commune, "BIHOR" county
[#4424](https://github.com/peviitor-ro/ui.orase/issues/4424)

Expected results:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed : "Sat Remetea, BIHOR (Remetea)"

Actual result (displayed):
The STEP have request to displayed "Village Remetea, BIHOR(Remetea)"

**All STEPS (from 1 to 5) have "VILLAGE" instead of "SAT"**
