### ISSUE TITLE
"Murta","Toceni" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Catalinay** [peviitor-ro/ui.orase#4739]
Description: 
When user writes "Murta","Toceni" the locations appear in the drop-down menu next to the comune and the county which is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)
	
Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Catalinay** [comment]
> **Step 1**
Write in the search bar "Murta"	

**Expected results** 
The location appears in the drop-down menu as "Sat Murta, DOLJ, (Dobrești)"

**Comment by Catalinay** [comment]
> **Step 2**
Press "x" button.
	
**Expected results** 
The location was deleted from the search bar.

**Comment by Catalinay** [comment]
> **Step 1**
Write in the search bar "Toceni"	

**Expected results** 
The location appears in the drop-down menu as "Sat Toceni, DOLJ, (Dobrești)"

**Comment by yonutzu** [comment]
Environment: ui.orase
URL:  https://peviitor-ro.github.io/ui.orase/
Browser: Chrome 124
OS: Windows 11

Steps to reproduce:
1 Open the @Adelina Guliman Test case ui.orase
2 Check TC ' "Murta","Toceni" are listed in the drop-down menu' 
3 Verify the steps

Expected results:
Steps are displayed in ascending order

Actual result (displayed):
Instead of step 3 is written "Step1"

![Image](https://github.com/peviitor-ro/ui.orase/assets/76839121/c6d783a4-8906-432b-b00f-6c15710d8c8f)

**Comment by Catalinay** [comment]
Am modificat, poti retesta.
