### ISSUE TITLE
"După Deal", "Șipot", "Valea" are listed in the drop-down menu

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#5836]
Description: 
When user writes ”După Deal”, "Șipot" and "Valea" the locations appear in the drop-down menu next to the comune and the county which is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Write in the search bar "După Deal"

**Expected results** 
The location appears in the drop-down menu as "**Sat** După Deal, **DÂMBOVIȚA** (Pietrari)".

**Comment by AdelinaGuliman** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by AdelinaGuliman** [comment]
> **Step 3**
Write in the search bar "Șipot"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Șipot, **DÂMBOVIȚA** (Petrești)".

**Comment by AdelinaGuliman** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by AdelinaGuliman** [comment]
> **Step 5**
Write in the search bar "Valea"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Valea, **DÂMBOVIȚA** (Petrești)".

**Comment by yonutzu** [comment]
ENVIROMENT: Run Tests: 5836
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Google Chrome
OS: Windows 11 Pro

STEPS TO REPRODUCE:

Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
Check TC : "Șipot", "Valea"are listed in the drop-down
https://github.com/peviitor-ro/ui.orase/issues/5836
EXPECTED RESULTS:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed :
STEP3: According to the law , the locations should appear in the drop-down menu as "Sat Sipot,Dambovita(Pietrari)".
ACTUAL RESULTS:
STEPS ( 3 and 5) have "(Petrești)" instead of "(Petrari)".

![Image](https://github.com/peviitor-ro/ui.orase/assets/76839121/bff7aa8e-43dd-43b8-a94c-87007dc7a937)
![Image](https://github.com/peviitor-ro/ui.orase/assets/76839121/81e0fa89-fe4c-40e7-aab0-7ffd6542c8c3)

**Comment by AdelinaGuliman** [comment]
Fixed! You can retest
