### ISSUE TITLE
"Brașov" county is listed in the drop-down menu

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#798]
Description: 
The "Brașov" county appears in the drop-down menu alongside the rest of the counties in Romania according to [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Click on the search bar.

**Expected results** 
The county appears in the drop-down menu as "Brașov"

**Comment by Florin201092** [comment]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "Brașov" in the search bar

EXPECTED RESULTS:
The location is listed in the drop-down menu as "Municipiul Brașov, Brașov".

ACTUAL RESULTS:
There are three options instead of two. The user should be able to see only "Municipiul Brașov, Brașov" and "Judetul Brașov".




![Image](https://github.com/peviitor-ro/ui.orase/assets/23164347/17fd2451-86c4-4995-9c5c-ce9d8e619bc6)




![Image](https://github.com/peviitor-ro/ui.orase/assets/23164347/bb1b9509-164f-4d1d-9797-5f9e480e9926)
