### ISSUE TITLE
"București" county is listed in the drop-down menu

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#800]
Description: 
The "București" county appears in the drop-down menu alongside the rest of the counties in Romania according to [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Click on the search bar.

**Expected results** 
The county appears in the drop-down menu as "București"

**Comment by Florin201092** [comment]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "București" in the search bar

EXPECTED RESULTS:
The location is listed in the drop-down menu as "Municipiul București".

ACTUAL RESULTS:
"Municipiul București" doesn't exist in the drop-down menu. Also, the user should be able to see only "Municipiul București" because "Judetul Bucuresti" doesn't exist.



![Image](https://github.com/peviitor-ro/ui.orase/assets/23164347/f23f9d28-391d-4acd-a3a0-9269d9ea63cb)
