### ISSUE TITLE
"Buzău" county is listed in the drop-down menu

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#801]
Description: 
The "Buzău" county appears in the drop-down menu alongside the rest of the counties in Romania according to [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Click on the search bar.

**Expected results** 
The county appears in the drop-down menu as "Buzău"

**Comment by Florin201092** [comment]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "Buzău" in the search bar

EXPECTED RESULTS:
The location is listed in the drop-down menu as "Municipiul Buzău, Buzău".

ACTUAL RESULTS:
There are three options instead of two. The user should be able to see only "Municipiul Buzău, Buzău" and "Judetul Buzău".




![Image](https://github.com/peviitor-ro/ui.orase/assets/23164347/505a8f78-b940-4f2b-afec-9cac7310b753)





![Image](https://github.com/peviitor-ro/ui.orase/assets/23164347/4da70b15-db12-4ebe-b0bb-511276ff4aca)
