### ISSUE TITLE
"Călărași" county is listed in the drop-down menu

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#803]
Description: 
The "Călărași" county appears in the drop-down menu alongside the rest of the counties in Romania according to [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Click on the search bar.

**Expected results** 
The county appears in the drop-down menu as "Călărași"

**Comment by Florin201092** [comment]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "Călărași" in the search bar

EXPECTED RESULTS:
The location is listed in the drop-down menu as "Municipiul Călărași, Călărași".

ACTUAL RESULTS:
There are three options instead of two. The user should be able to see only "Municipiul Călărași, Călărași" and "Judetul Călărași".




![Image](https://github.com/peviitor-ro/ui.orase/assets/23164347/f276ded4-56be-4b45-82e9-8cfef0c31f7b)




![Image](https://github.com/peviitor-ro/ui.orase/assets/23164347/7ad22f0c-939a-4517-9ebc-c225c86f149e)
